date=2023-11-14 19:11:02
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1676, in closeEvent
    self.export_cache_all()
  File "D:\R2A\R2A.py", line 1530, in export_cache_all
    df = pd.DataFrame(data).T
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 625, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 19:09:37
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1676, in closeEvent
    self.export_cache_all()
  File "D:\R2A\R2A.py", line 1530, in export_cache_all
    df = pd.DataFrame(data).T
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 625, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 18:44:47
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 18:44:39
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 18:42:07
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 18:41:59
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 16:21:49
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 318, in <lambda>
    self.btn_item_txt_2.clicked.connect(lambda:self.additemText("additems"))
  File "D:\R2A\R2A.py", line 619, in additemText
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'additems_琿.txt'


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:07:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    df = df.fillna('')
AttributeError: 'int' object has no attribute 'fillna'


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:07:10
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df != None and df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:06:33
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:06:20
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:06:16
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1629, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:05:22
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1629, in load_preset
    df = df.fillna('')
AttributeError: 'XLRDError' object has no attribute 'fillna'


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 13:03:07
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1625, in load_preset
    df = df.fillna('')
AttributeError: 'XLRDError' object has no attribute 'fillna'


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 12:58:22
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 12:46:11
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 12:46:08
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 12:45:58
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 11:37:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
date=2023-11-14 11:37:24
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
