date=2023-11-17 10:45:08
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 461, in optimizeCurrentAppPos
    if currentAppName == "" :
NameError: name 'currentAppName' is not defined


────────────────────────────────────────
date=2023-11-15 17:42:00
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 348, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 961, in load_preset
    if pd.isna(df) :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-15 17:39:44
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 987, in load_preset
    if df == None :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-15 17:39:43
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 987, in load_preset
    if df == None :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-15 17:39:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 327, in <lambda>
    self.btn_item_preset_load.clicked.connect(lambda : self.load_preset('item'))
  File "D:\R2A\R2A.py", line 987, in load_preset
    if df == None :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-15 16:46:35
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 985, in load_preset
    if df == None :
UnboundLocalError: local variable 'df' referenced before assignment


────────────────────────────────────────
date=2023-11-15 16:46:32
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 985, in load_preset
    if df == None :
UnboundLocalError: local variable 'df' referenced before assignment


────────────────────────────────────────
date=2023-11-15 16:45:43
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 986, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:45:38
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 986, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:45:24
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 986, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:45:18
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 986, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:45:17
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 986, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:45:14
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 360, in <lambda>
    self.btn_item_preset_3.clicked.connect(lambda : self.delete_preset("item"))
  File "D:\R2A\R2A.py", line 904, in delete_preset
    f'preset_{preset_type}_{preset_name}.xlsx')
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\data\\preset\\preset_item_.xlsx'


────────────────────────────────────────
date=2023-11-15 16:44:48
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 380, in <lambda>
    self.btn_cmd_preset_4.clicked.connect(lambda : self.delete_preset("cmd"))
  File "D:\R2A\R2A.py", line 904, in delete_preset
    os.remove(directory_path)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\data\\preset\\preset_cmd_.xlsx'


────────────────────────────────────────
date=2023-11-15 16:44:46
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 380, in <lambda>
    self.btn_cmd_preset_4.clicked.connect(lambda : self.delete_preset("cmd"))
  File "D:\R2A\R2A.py", line 904, in delete_preset
    os.remove(directory_path)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\data\\preset\\preset_cmd_.xlsx'


────────────────────────────────────────
date=2023-11-15 16:43:52
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 380, in <lambda>
    self.btn_cmd_preset_4.clicked.connect(lambda : self.delete_preset("cmd"))
  File "D:\R2A\R2A.py", line 900, in delete_preset
    os.remove(directory_path)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\data\\preset\\preset_cmd_.xlsx'


────────────────────────────────────────
date=2023-11-15 16:41:38
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 352, in <lambda>
    getattr(self, f'btn_cmd_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'cmd'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 958, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:40:50
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 352, in <lambda>
    getattr(self, f'btn_cmd_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'cmd'))
  File "D:\R2A\R2A.py", line 894, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 956, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:39:28
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 348, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 956, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:39:26
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 348, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 956, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:38:20
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 348, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 955, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 25, in load_preset
    return pd.read_csv(file_path, sep='\t', encoding='utf-16')
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Python39\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeError: UTF-16 stream does not start with BOM


────────────────────────────────────────
date=2023-11-15 16:37:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 355, in <lambda>
    self.btn_cmd_preset_1.clicked.connect(lambda : self.파일열기(self.input_cmd_preset_path.text()))
AttributeError: 'WindowClass' object has no attribute 'input_cmd_preset_path'


────────────────────────────────────────
date=2023-11-15 16:37:31
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 355, in <lambda>
    self.btn_cmd_preset_1.clicked.connect(lambda : self.파일열기(self.input_cmd_preset_path.text()))
AttributeError: 'WindowClass' object has no attribute 'input_cmd_preset_path'


────────────────────────────────────────
date=2023-11-15 16:37:25
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 348, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 956, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-15 16:26:54
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 360, in <lambda>
    self.btn_item_preset_3.clicked.connect(lambda : self.delete_preset("item"))
  File "D:\R2A\R2A.py", line 900, in delete_preset
    os.remove(directory_path)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\R2A\\data\\preset\\preset_item_test1'


────────────────────────────────────────
date=2023-11-15 16:09:43
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 332, in <lambda>
    self.btn_item_preset_0.clicked.connect(lambda : self.파일열기(os.path.join(self.input_preset_path.text(),\
AttributeError: 'WindowClass' object has no attribute 'input_preset_path'


────────────────────────────────────────
date=2023-11-15 16:09:13
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 332, in <lambda>
    self.btn_item_preset_0.clicked.connect(lambda : self.파일열기(os.path.join(self.input_preset_path.text(),\
AttributeError: 'WindowClass' object has no attribute 'input_preset_path'


────────────────────────────────────────
date=2023-11-15 16:09:05
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_item_preset_1.clicked.connect(lambda : self.파일열기(self.input_preset_path.text()))
AttributeError: 'WindowClass' object has no attribute 'input_preset_path'


────────────────────────────────────────
date=2023-11-15 16:08:07
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_item_preset_1.clicked.connect(lambda : self.파일열기(self.input_preset_path.text()))
AttributeError: 'WindowClass' object has no attribute 'input_preset_path'


────────────────────────────────────────
date=2023-11-15 16:08:04
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 332, in <lambda>
    self.btn_item_preset_0.clicked.connect(lambda : self.파일열기(os.path.join(self.input_preset_path.text(),\
AttributeError: 'WindowClass' object has no attribute 'input_item_preset_path'


────────────────────────────────────────
date=2023-11-15 16:08:03
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_item_preset_1.clicked.connect(lambda : self.파일열기(self.input_preset_path.text()))
AttributeError: 'WindowClass' object has no attribute 'input_preset_path'


────────────────────────────────────────
date=2023-11-15 16:08:02
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 332, in <lambda>
    self.btn_item_preset_0.clicked.connect(lambda : self.파일열기(os.path.join(self.input_preset_path.text(),\
AttributeError: 'WindowClass' object has no attribute 'input_item_preset_path'


────────────────────────────────────────
date=2023-11-15 16:07:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 332, in <lambda>
    self.btn_item_preset_0.clicked.connect(lambda : self.파일열기(os.path.join(self.input_item_preset_path.text(),\
AttributeError: 'WindowClass' object has no attribute 'input_item_preset_path'


────────────────────────────────────────
date=2023-11-15 16:06:30
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 331, in <lambda>
    getattr(self, f'btn_item_preset_bookmark_{i}').clicked.connect(lambda _, x=i : self.load_preset_by_bookmark(x, 'item'))
  File "D:\R2A\R2A.py", line 908, in load_preset_by_bookmark
    self.load_preset(preset_type,preset_name)
  File "D:\R2A\R2A.py", line 1756, in load_preset
    getattr(self, f'input_{preset_name}_preset').setText(preset_name)
AttributeError: 'WindowClass' object has no attribute 'input_test_preset'


────────────────────────────────────────
date=2023-11-15 16:02:18
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 326, in <lambda>
    self.btn_item_preset_save.clicked.connect(lambda : self.save_preset('item'))
  File "D:\R2A\R2A.py", line 1700, in save_preset
    tempVal0 = getattr(self, f'input_additem_itemid_{i}').text()
AttributeError: 'WindowClass' object has no attribute 'input_additem_itemid_15'


────────────────────────────────────────
date=2023-11-15 15:58:19
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 326, in <lambda>
    self.btn_item_preset_save.clicked.connect(lambda : self.save_preset('item'))
  File "D:\R2A\R2A.py", line 1695, in save_preset
    pm.save_preset(f'{preset_type}_{preset_name}', df)
UnboundLocalError: local variable 'preset_name' referenced before assignment


────────────────────────────────────────
date=2023-11-15 15:36:18
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 359, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1167, in control_multi_cmd
    cursor = self.plainTextEdit.textCursor()
AttributeError: 'WindowClass' object has no attribute 'plainTextEdit'


────────────────────────────────────────
date=2023-11-15 15:30:15
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 359, in <lambda>
    getattr(self, f'btn_cmd_plus_{i}').clicked.connect(lambda _, x=i : self.control_multi_cmd(x))
  File "D:\R2A\R2A.py", line 1162, in control_multi_cmd
    total_text += f'\n{int(cur_text)+100}'
ValueError: invalid literal for int() with base 10: ''


────────────────────────────────────────
date=2023-11-15 14:57:01
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1582, in export_cache
    }
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Python39\lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Python39\lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
  File "C:\Python39\lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: './cache/cache.csv'


────────────────────────────────────────
date=2023-11-15 14:52:02
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1582, in export_cache
    data[key] = {
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Python39\lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Python39\lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
  File "C:\Python39\lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: './cache/cache.csv'


────────────────────────────────────────
date=2023-11-15 14:39:30
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1073, in set_check_box_state
    getattr(self, f'{attr_str}{i}').setCheckState(state)
AttributeError: 'WindowClass' object has no attribute 'check_item_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 321, in <lambda>
    self.btn_item_0.clicked.connect(lambda : self.set_check_box_state("check_item_",999,2))
  File "D:\R2A\R2A.py", line 1075, in set_check_box_state
    self.show_statusbar_msg(e)
  File "D:\R2A\R2A.py", line 1674, in show_statusbar_msg
    self.statusbar.showMessage(msg)
TypeError: showMessage(self, message: str, msecs: int = 0): argument 1 has unexpected type 'AttributeError'


────────────────────────────────────────
date=2023-11-15 12:33:24
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 439, in optimizeCurrentAppPos
    if currentAppName == "" :
NameError: name 'currentAppName' is not defined


────────────────────────────────────────
date=2023-11-15 12:07:51
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_save.clicked.connect(lambda : self.save_preset('cmd'))
  File "D:\R2A\R2A.py", line 1621, in save_preset
    self.set_statusbar('need to insert preset name')
  File "D:\R2A\R2A.py", line 1679, in set_statusbar
    self.statusbar.setText(msg)
AttributeError: 'QStatusBar' object has no attribute 'setText'


────────────────────────────────────────
date=2023-11-14 19:11:02
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1676, in closeEvent
    self.export_cache_all()
  File "D:\R2A\R2A.py", line 1530, in export_cache_all
    df = pd.DataFrame(data).T
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 625, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index


────────────────────────────────────────
date=2023-11-14 19:09:37
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 1676, in closeEvent
    self.export_cache_all()
  File "D:\R2A\R2A.py", line 1530, in export_cache_all
    df = pd.DataFrame(data).T
  File "C:\Python39\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Python39\lib\site-packages\pandas\core\internals\construction.py", line 625, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index


────────────────────────────────────────
date=2023-11-14 18:44:47
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


────────────────────────────────────────
date=2023-11-14 18:44:39
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


────────────────────────────────────────
date=2023-11-14 18:42:07
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


────────────────────────────────────────
date=2023-11-14 18:41:59
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 268, in <lambda>
    self.btn_temp_1.clicked.connect(lambda : self.set_button_styles(999))
  File "D:\R2A\R2A.py", line 1417, in set_button_styles
    if 'item_img' in widget.objectName :
TypeError: argument of type 'builtin_function_or_method' is not iterable


────────────────────────────────────────
date=2023-11-14 16:21:49
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 318, in <lambda>
    self.btn_item_txt_2.clicked.connect(lambda:self.additemText("additems"))
  File "D:\R2A\R2A.py", line 619, in additemText
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'additems_룬.txt'


────────────────────────────────────────
date=2023-11-14 13:07:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    df = df.fillna('')
AttributeError: 'int' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-14 13:07:10
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df != None and df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-14 13:06:33
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-14 13:06:20
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1626, in load_preset
    if df == -1 :
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().


────────────────────────────────────────
date=2023-11-14 13:06:16
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1629, in load_preset
    df = df.fillna('')
AttributeError: 'NoneType' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-14 13:05:22
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 335, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1629, in load_preset
    df = df.fillna('')
AttributeError: 'XLRDError' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-14 13:03:07
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1625, in load_preset
    df = df.fillna('')
AttributeError: 'XLRDError' object has no attribute 'fillna'


────────────────────────────────────────
date=2023-11-14 12:58:22
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


────────────────────────────────────────
date=2023-11-14 12:46:11
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


────────────────────────────────────────
date=2023-11-14 12:46:08
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


────────────────────────────────────────
date=2023-11-14 12:45:58
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 334, in <lambda>
    self.btn_cmd_preset_load.clicked.connect(lambda : self.load_preset('cmd'))
  File "D:\R2A\R2A.py", line 1624, in load_preset
    df = pm.load_preset(f'{preset_type}_{preset_name}')
  File "D:\R2A\PresetManager.py", line 22, in load_preset
    return pd.read_excel(file_path)
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 25, in __init__
    super().__init__(filepath_or_buffer, storage_options=storage_options)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_base.py", line 420, in __init__
    self.book = self.load_workbook(self.handles.handle)
  File "C:\Python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 38, in load_workbook
    return open_workbook(file_contents=data)
  File "C:\Python39\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 68, in open_workbook_xls
    bk.biff2_8_load(
  File "C:\Python39\lib\site-packages\xlrd\book.py", line 645, in biff2_8_load
    raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document


────────────────────────────────────────
date=2023-11-14 11:37:36
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


────────────────────────────────────────
date=2023-11-14 11:37:24
user=mssung

Traceback (most recent call last):
  File "D:\R2A\R2A.py", line 889, in addCmdPresetBookmark
    getattr(self, f'btn_cmd_preset_bookmark_{target_preset_num}').setText()
TypeError: setText(self, text: str): not enough arguments


────────────────────────────────────────
